version: '2'
services:
  redis:
    image: redis:3.2
    restart: always
  app:
    depends_on:
      - redis
    restart: always
    image: bbs-be:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PWD=${DATABASE_PWD}
      - REDIS_HOST=redis
